### PR TITLE
Add option to estimate partially pooled embeddings with lme4

### PR DESCRIPTION
**Pull request by alexpghayes**
Documentation updates coming in just a second.

### CODE REVIEW

**Comment by topepo** [comment]
I started working on using `glmnet` for this yesterday. Can you spin this off into its own step? I think that I'm doing to rename `step_embed` to `step_effects` that will just do `glm`. `step_byeseffects` will be stan only. Maybe name this `step_mixedeffects`? I'm open to other names (since this one is a little deceiving).

**Comment by alexpghayes** [comment]
Can do. I think `step_embed` and `step_effects` are both misleading names. I've seen this transformation called several things, but most commonly a *likelihood encoding*. I'd prefer a naming scheme along the lines of:

- step_llhencode_glm
- step_llhencode_glmnet
- step_llhencode_stan
- step_llhencode_lme4

Having both `glm` and `glmnet` variants may prove confusing as well, so we may want to offer only one of those.

**Comment by topepo** [comment]
I'm good with `step_embed`. How about `step_lencode_glm`, `step_lencode_bayes`, and `step_lencode_mixed`?

**Comment by topepo** [comment]
I would discard the `pkgdown` changes for now until we settle on names.

**Comment by alexpghayes** [comment]
I like the `step_lencode_*` strategy. Will update when I next have a break on the broom front.

**Comment by topepo** [comment]
Actually... it would be more consistent with existing steps (like `knnimpute`, `bagimpute` etc) to use `step_*_lencode`

**Comment by alexpghayes** [comment]
It looks like this got implemented at some point? Should I go ahead and close?

**Comment by topepo** [comment]
I'll close. Sorry for the confusion.

**Pull request closed without merging**
