### PR TITLE
Fix the outcome parameter's description of `step_embed()`

### PR DESCRIPTION
**Pull request by asiripanich**
It seems to me that it is no longer the case that `outcome` can only be numeric or two-level factors. Please correct me if I'm wrong. :)

### CODE REVIEW

**Comment by juliasilge** [comment]
Thank you so much for this contribution @asiripanich! 👍 

Can you create a [reprex](https://reprex.tidyverse.org/) (a minimal reproducible example) demonstrating that multinomial outcomes are supported, for us to have here in the issue? The goal of a reprex is to make it easier for us to see details like this and share them.

If you've never heard of a reprex before, you may want to start with the [tidyverse.org help](https://www.tidyverse.org/help/) page. You may already have reprex installed (it comes with the tidyverse package), but if not you can install it with:

```r
install.packages("reprex")
```

Thanks! 🙌

**Comment by asiripanich** [comment]
``` r
library(tidymodels)
library(embed)

data(okc)
okc_sample <- sample_n(okc, size = 1000)

str(okc_sample)
#> tibble[,6] [1,000 x 6] (S3: tbl_df/tbl/data.frame)
#>  $ age     : int [1:1000] 30 37 21 22 22 30 42 44 25 25 ...
#>  $ diet    : chr [1:1000] NA NA "mostly anything" NA ...
#>  $ height  : int [1:1000] 60 75 64 73 63 74 71 70 64 67 ...
#>  $ location: chr [1:1000] "berkeley" "san francisco" "richmond" "berkeley" ...
#>  $ date    : Date[1:1000], format: "2012-06-19" "2012-01-18" ...
#>  $ Class   : Factor w/ 2 levels "stem","other": 2 1 2 1 2 2 2 2 2 2 ...

recipe(diet ~ ., data = okc_sample) %>%
  step_naomit(everything()) %>%
  step_embed(location, outcome = vars(diet)) %>%
  prep(training = okc_sample, retain = TRUE) %>%
  bake(okc_sample)
#> # A tibble: 601 x 7
#>      age height date       Class diet          location_embed_1 location_embed_2
#>    <int>  <int> <date>     <fct> <fct>                    <dbl>            <dbl>
#>  1    21     64 2012-06-30 other mostly anyth~         -0.0493          -0.00781
#>  2    22     63 2012-06-29 other anything              -0.0169          -0.0285 
#>  3    30     74 2012-06-30 other anything              -0.0121          -0.0471 
#>  4    44     70 2012-06-30 other mostly anyth~         -0.0121          -0.0471 
#>  5    25     64 2012-06-30 other mostly anyth~         -0.0121          -0.0471 
#>  6    25     67 2012-06-26 other mostly anyth~         -0.0121          -0.0471 
#>  7    33     70 2012-06-29 other mostly veget~         -0.0121          -0.0471 
#>  8    62     61 2012-06-28 other mostly veget~         -0.00641         -0.0107 
#>  9    36     72 2012-06-28 stem  mostly anyth~         -0.0121          -0.0471 
#> 10    47     69 2012-06-29 stem  strictly any~         -0.00118         -0.00639
#> # ... with 591 more rows
```

<sup>Created on 2021-05-13 by the [reprex package](https://reprex.tidyverse.org) (v2.0.0)</sup>

<details style="margin-bottom:10px;">
<summary>
Session info
</summary>

``` r
sessioninfo::session_info()
#> - Session info ---------------------------------------------------------------
#>  setting  value                       
#>  version  R version 4.0.5 (2021-03-31)
#>  os       Windows 10 x64              
#>  system   x86_64, mingw32             
#>  ui       RTerm                       
#>  language (EN)                        
#>  collate  English_Australia.1252      
#>  ctype    English_Australia.1252      
#>  tz       Australia/Sydney            
#>  date     2021-05-13                  
#> 
#> - Packages -------------------------------------------------------------------
#>  package      * version    date       lib source        
#>  assertthat     0.2.1      2019-03-21 [1] CRAN (R 4.0.5)
#>  backports      1.2.1      2020-12-09 [1] CRAN (R 4.0.3)
#>  base64enc      0.1-3      2015-07-28 [1] CRAN (R 4.0.3)
#>  broom        * 0.7.6      2021-04-05 [1] CRAN (R 4.0.5)
#>  class          7.3-18     2021-01-24 [2] CRAN (R 4.0.5)
#>  cli            2.5.0      2021-04-26 [1] CRAN (R 4.0.5)
#>  codetools      0.2-18     2020-11-04 [2] CRAN (R 4.0.5)
#>  colorspace     2.0-0      2020-11-11 [1] CRAN (R 4.0.5)
#>  crayon         1.4.1      2021-02-08 [1] CRAN (R 4.0.5)
#>  DBI            1.1.1      2021-01-15 [1] CRAN (R 4.0.5)
#>  dials        * 0.0.9      2020-09-16 [1] CRAN (R 4.0.5)
#>  DiceDesign     1.9        2021-02-13 [1] CRAN (R 4.0.5)
#>  digest         0.6.27     2020-10-24 [1] CRAN (R 4.0.5)
#>  dplyr        * 1.0.6      2021-05-05 [1] CRAN (R 4.0.5)
#>  ellipsis       0.3.1      2020-05-15 [1] CRAN (R 4.0.5)
#>  embed        * 0.1.4.9000 2021-05-12 [1] local         
#>  evaluate       0.14       2019-05-28 [1] CRAN (R 4.0.5)
#>  fansi          0.4.2      2021-01-15 [1] CRAN (R 4.0.5)
#>  foreach        1.5.1      2020-10-15 [1] CRAN (R 4.0.5)
#>  fs             1.5.0      2020-07-31 [1] CRAN (R 4.0.5)
#>  furrr          0.2.2      2021-01-29 [1] CRAN (R 4.0.5)
#>  future         1.21.0     2020-12-10 [1] CRAN (R 4.0.5)
#>  generics       0.1.0      2020-10-31 [1] CRAN (R 4.0.5)
#>  ggplot2      * 3.3.3      2020-12-30 [1] CRAN (R 4.0.5)
#>  globals        0.14.0     2020-11-22 [1] CRAN (R 4.0.3)
#>  glue           1.4.2      2020-08-27 [1] CRAN (R 4.0.5)
#>  gower          0.2.2      2020-06-23 [1] CRAN (R 4.0.3)
#>  GPfit          1.0-8      2019-02-08 [1] CRAN (R 4.0.5)
#>  gtable         0.3.0      2019-03-25 [1] CRAN (R 4.0.5)
#>  highr          0.8        2019-03-20 [1] CRAN (R 4.0.5)
#>  htmltools      0.5.1.1    2021-01-22 [1] CRAN (R 4.0.5)
#>  infer        * 0.5.4      2021-01-13 [1] CRAN (R 4.0.5)
#>  ipred          0.9-11     2021-03-12 [1] CRAN (R 4.0.5)
#>  iterators      1.0.13     2020-10-15 [1] CRAN (R 4.0.5)
#>  jsonlite       1.7.2      2020-12-09 [1] CRAN (R 4.0.5)
#>  keras          2.4.0      2021-03-29 [1] CRAN (R 4.0.5)
#>  knitr          1.31       2021-01-27 [1] CRAN (R 4.0.5)
#>  lattice        0.20-41    2020-04-02 [2] CRAN (R 4.0.5)
#>  lava           1.6.9      2021-03-11 [1] CRAN (R 4.0.5)
#>  lhs            1.1.1      2020-10-05 [1] CRAN (R 4.0.5)
#>  lifecycle      1.0.0      2021-02-15 [1] CRAN (R 4.0.5)
#>  listenv        0.8.0      2019-12-05 [1] CRAN (R 4.0.5)
#>  lubridate      1.7.10     2021-02-26 [1] CRAN (R 4.0.5)
#>  magrittr       2.0.1      2020-11-17 [1] CRAN (R 4.0.5)
#>  MASS           7.3-53.1   2021-02-12 [2] CRAN (R 4.0.5)
#>  Matrix         1.3-2      2021-01-06 [2] CRAN (R 4.0.5)
#>  modeldata    * 0.1.0      2020-10-22 [1] CRAN (R 4.0.5)
#>  munsell        0.5.0      2018-06-12 [1] CRAN (R 4.0.5)
#>  nnet           7.3-15     2021-01-24 [2] CRAN (R 4.0.5)
#>  parallelly     1.25.0     2021-04-30 [1] CRAN (R 4.0.5)
#>  parsnip      * 0.1.5      2021-01-19 [1] CRAN (R 4.0.5)
#>  pillar         1.6.0      2021-04-13 [1] CRAN (R 4.0.5)
#>  pkgconfig      2.0.3      2019-09-22 [1] CRAN (R 4.0.5)
#>  plyr           1.8.6      2020-03-03 [1] CRAN (R 4.0.5)
#>  png            0.1-7      2013-12-03 [1] CRAN (R 4.0.3)
#>  pROC           1.17.0.1   2021-01-13 [1] CRAN (R 4.0.5)
#>  prodlim        2019.11.13 2019-11-17 [1] CRAN (R 4.0.5)
#>  ps             1.6.0      2021-02-28 [1] CRAN (R 4.0.5)
#>  purrr        * 0.3.4      2020-04-17 [1] CRAN (R 4.0.5)
#>  R6             2.5.0      2020-10-28 [1] CRAN (R 4.0.5)
#>  rappdirs       0.3.3      2021-01-31 [1] CRAN (R 4.0.5)
#>  Rcpp           1.0.6      2021-01-15 [1] CRAN (R 4.0.4)
#>  recipes      * 0.1.16     2021-04-16 [1] CRAN (R 4.0.5)
#>  reprex         2.0.0      2021-04-02 [1] CRAN (R 4.0.5)
#>  reticulate     1.20       2021-05-03 [1] CRAN (R 4.0.5)
#>  rlang          0.4.10     2020-12-30 [1] CRAN (R 4.0.5)
#>  rmarkdown      2.7        2021-02-19 [1] CRAN (R 4.0.5)
#>  rpart          4.1-15     2019-04-12 [2] CRAN (R 4.0.5)
#>  rsample      * 0.1.0      2021-05-08 [1] CRAN (R 4.0.5)
#>  rstudioapi     0.13       2020-11-12 [1] CRAN (R 4.0.5)
#>  scales       * 1.1.1      2020-05-11 [1] CRAN (R 4.0.5)
#>  sessioninfo    1.1.1      2018-11-05 [1] CRAN (R 4.0.5)
#>  stringi        1.5.3      2020-09-09 [1] CRAN (R 4.0.3)
#>  stringr        1.4.0      2019-02-10 [1] CRAN (R 4.0.5)
#>  styler         1.4.1      2021-03-30 [1] CRAN (R 4.0.5)
#>  survival       3.2-10     2021-03-16 [2] CRAN (R 4.0.5)
#>  tensorflow     2.4.0      2021-03-23 [1] CRAN (R 4.0.5)
#>  tfruns         1.5.0      2021-02-26 [1] CRAN (R 4.0.5)
#>  tibble       * 3.1.0      2021-02-25 [1] CRAN (R 4.0.5)
#>  tidymodels   * 0.1.3      2021-04-19 [1] CRAN (R 4.0.5)
#>  tidyr        * 1.1.3      2021-03-03 [1] CRAN (R 4.0.5)
#>  tidyselect     1.1.1      2021-04-30 [1] CRAN (R 4.0.5)
#>  timeDate       3043.102   2018-02-21 [1] CRAN (R 4.0.5)
#>  tune         * 0.1.5      2021-04-23 [1] CRAN (R 4.0.5)
#>  utf8           1.2.1      2021-03-12 [1] CRAN (R 4.0.5)
#>  uwot           0.1.10     2020-12-15 [1] CRAN (R 4.0.5)
#>  vctrs          0.3.7      2021-03-29 [1] CRAN (R 4.0.5)
#>  whisker        0.4        2019-08-28 [1] CRAN (R 4.0.5)
#>  withr          2.4.2      2021-04-18 [1] CRAN (R 4.0.5)
#>  workflows    * 0.2.2      2021-03-10 [1] CRAN (R 4.0.5)
#>  workflowsets * 0.0.2      2021-04-16 [1] CRAN (R 4.0.5)
#>  xfun           0.22       2021-03-11 [1] CRAN (R 4.0.5)
#>  yaml           2.2.1      2020-02-01 [1] CRAN (R 4.0.4)
#>  yardstick    * 0.0.8      2021-03-28 [1] CRAN (R 4.0.5)
#>  zeallot        0.1.0      2018-01-28 [1] CRAN (R 4.0.5)
#> 
#> [1] C:/Users/amarin/Documents/R/win-library/4.0
#> [2] C:/Program Files/R/R-4.0.5/library
```

</details>

**Comment by asiripanich** [comment]
@juliasilge Not sure what the actions are failing. I only removed one line of comment. :(

**Comment by asiripanich** [comment]
`tidy_trained$terms` in 

https://github.com/tidymodels/embed/blob/ad827ac5d57c7a46a1ef9be9276b590465b780b0/tests/testthat/test_discretize_xgb.R#L479-L482

returns 

```r
tidy_trained$terms
 [1] "x" "x" "x" "x" "x" "x" "x" "z" "z" "z" "z"
```

Investigating..

**Comment by topepo** [comment]
It's due to how `xgboost` handles random numbers (and has been a thorn in our side repeatedly). Don't worry about it; I'll fix it in another PR.

**Pull request merged**
